version: 1.0.{build}

image:
  - Ubuntu
#  - Visual Studio 2017
platform: x64
configuration: Release

clone_folder: c:\projects\DirectXShaderCompiler

environment:
  HLSL_SRC_DIR: c:\projects\DirectXShaderCompiler
  HLSL_BLD_DIR: c:\projects\DirectXShaderCompiler\build
  ARTIFACTS_ZIP_NAME: dxc-artifacts.zip

install:
- git submodule update --init
- cmd: set PATH=C:\ninja;C:\Python36;%PATH%
#- sh: wget -q https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-mac.zip;
#- sh: unzip -q ninja-mac.zip;
#- sh: chmod +x ninja;
#- sh: export PATH="$PWD:$PATH";

before_build:
- cmd: call utils\hct\hctstart %HLSL_SRC_DIR% %HLSL_BLD_DIR%

build_script:
- cmd: call utils\hct\hctbuild -%PLATFORM% -%CONFIGURATION% -spirvtest
- sh: cmake . -GNinja $(cat ./utils/cmake-predefined-config-params) -DSPIRV_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
- sh: ninja

test_script:
- ps:  utils\appveyor\appveyor_test.ps1
- cmd: call utils\hct\hcttest -rel spirv_only
- sh: ./bin/dxc --help
- sh: ./bin/dxc -T ps_6_0 ../tools/clang/test/CodeGenSPIRV/passthru-ps.hlsl2spv
- sh: ./bin/dxc -T ps_6_0 -Fo passthru-ps.dxil ../tools/clang/test/CodeGenSPIRV/passthru-ps.hlsl2spv
- sh: ./bin/dxc -T ps_6_0 -Fo passthru-ps.spv ../tools/clang/test/CodeGenSPIRV/passthru-ps.hlsl2spv -spirv
- sh: ./bin/clang-spirv-tests --spirv-test-root ../tools/clang/test/CodeGenSPIRV/
- sh: ./bin/clang-hlsl-tests --HlslDataDir $PWD/../tools/clang/test/HLSL/

after_test:
- cmd: cd build\%CONFIGURATION%
- cmd: echo %APPVEYOR_REPO_COMMIT% > GIT-COMMIT.txt
- cmd: xcopy "%HLSL_SRC_DIR%\include\dxc" include\dxc /s /i /y
- cmd: 7z a %ARTIFACTS_ZIP_NAME% include lib\d*.lib bin\d*.exe bin\d*.dll bin\d*.pdb bin\HLSLHost.exe GIT-COMMIT.txt

artifacts:
- path: build\$(configuration)\$(ARTIFACTS_ZIP_NAME)

notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
